#Independent settings for the planner's costmap
global_costmap:
    
    # global_frame: map
    
    update_frequency: 5.0
    publish_frequency: 2.0
    static_map: true
    width: 40
    height: 40
    origin_x: -20.0
    origin_y: -20.0
    #rolling_window: false
    unknown_cost_value: 255
