#Independent settings for the local costmap
local_costmap:
    # publish_voxel_map: true
    
    # global_frame: map
    
    update_frequency: 5.0 # prev 5.0
    publish_frequency: 3.0
    static_map: false

    rolling_window: true
    width: 5.0      #prev 10.0
    height: 5.0     #prev 10.0
    resolution: 0.1 #prev 0.025
    origin_x: 0.0
    origin_y: 0.0
